version: '3'
services:
  sales-service1:
    image: adoptopenjdk/openjdk12:latest
    container_name: sales-service1
    volumes:
      - ./jar:/jar
    environment:
      - "TZ=America/Sao_Paulo"
      - "SPRING_PROFILES_ACTIVE=development"
    network_mode: host
    entrypoint:
      - "java"
      - "-server"
      - "-jar"
      - "./jar/sales.jar"
  sales-service2:
    image: adoptopenjdk/openjdk12:latest
    container_name: sales-service2
    volumes:
      - ./jar:/jar
    environment:
      - "TZ=America/Sao_Paulo"
      - "SPRING_PROFILES_ACTIVE=development"
      - "SERVER_PORT=9010"
    network_mode: host
    entrypoint:
      - "java"
      - "-server"
      - "-jar"
      - "./jar/sales.jar"